# Generated by Django 2.2.1 on 2019-05-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='dataAbertura',
            field=models.DateField(auto_now_add=True, verbose_name='ABERTO EM'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='idStatus',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='chamado.Status', verbose_name='STATUS'),
        ),
    ]
