# Generated by Django 2.1.7 on 2019-04-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20190402_1201'),
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAbertura', models.DateField(default=None, verbose_name='ABERTO EM')),
                ('dataFechamento', models.DateField(blank=True, default=None, null=True, verbose_name='CONCLUÍDO EM')),
                ('observacao', models.CharField(max_length=200, verbose_name='OBSERVAÇÃO')),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Endereco', verbose_name='ENDEREÇO')),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Eventos', verbose_name='SERVIÇO')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa', verbose_name='PESSOA')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Status', verbose_name='STATUS')),
            ],
        ),
        migrations.DeleteModel(
            name='Chamado',
        ),
    ]
