# Generated by Django 2.1.7 on 2019-05-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_auto_20190510_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='observacaoOrgao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RETORNO DO ÓRGÃO'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='dataFechamento',
            field=models.DateField(auto_now=True, verbose_name='CONCLUÍDO EM'),
        ),
    ]
