# Generated by Django 2.1.7 on 2019-04-09 00:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='BAIRRO')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, verbose_name='NÚMERO')),
                ('complemento', models.CharField(max_length=50, verbose_name='COMPLEMENTO')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='PESSOA')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('senha', models.CharField(max_length=11, verbose_name='SENHA')),
                ('email', models.CharField(max_length=100, verbose_name='E-MAIL')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='RUA')),
                ('idBairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Bairro', verbose_name='BAIRRO')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, verbose_name='NÚMERO')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='TIPO TELEFONE')),
            ],
        ),
        migrations.AddField(
            model_name='telefone',
            name='idTipoTelefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.TipoTelefone', verbose_name='TIPO TELEFONE'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='idRua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Rua', verbose_name='RUA'),
        ),
    ]
