# Generated by Django 2.1.7 on 2019-04-27 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='BAIRRO')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, verbose_name='NÚMERO')),
                ('complemento', models.CharField(max_length=50, verbose_name='COMPLEMENTO')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA')),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='RUA')),
                ('idBairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Bairro', verbose_name='BAIRRO')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, verbose_name='NÚMERO')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='TIPO TELEFONE')),
            ],
        ),
        migrations.AddField(
            model_name='telefone',
            name='idTipoTelefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.TipoTelefone', verbose_name='TIPO TELEFONE'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='idRua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Rua', verbose_name='RUA'),
        ),
    ]
