# Generated by Django 2.1.7 on 2019-03-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20190325_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotacao',
            name='observacao',
            field=models.CharField(default='nenhuma', max_length=200),
            preserve_default=False,
        ),
    ]
