# Generated by Django 2.1.7 on 2019-03-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_lotacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='dataAbertura',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dataFechamento',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='observacao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
