# Generated by Django 2.1.7 on 2019-04-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20190325_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='BAIRRO'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dataAbertura',
            field=models.DateField(default=None, verbose_name='ABERTO EM'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dataFechamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='CONCLUÍDO EM'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='idEndereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Endereco', verbose_name='ENDEREÇO'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Eventos', verbose_name='SERVIÇO'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa', verbose_name='PESSOA'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='idStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Status', verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='observacao',
            field=models.CharField(max_length=200, verbose_name='OBSERVAÇÃO'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=50, verbose_name='COMPLEMENTO'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='idBairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Bairro', verbose_name='BAIRRO'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa', verbose_name='PESSOA'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='RUA'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='NÚMERO'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='SERVIÇO'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idOrgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Orgao', verbose_name='ÓRGÃO'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='idOrgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Orgao', verbose_name='ÓRGÃO'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa', verbose_name='PESSOA'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='idTipoLotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.TipoLotacao', verbose_name='TIPO LOTAÇÃO'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='observacao',
            field=models.CharField(max_length=200, verbose_name='OBSERVAÇÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='DESCRIÇÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='ÓRGÃO'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-MAIL'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='PESSOA'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=11, verbose_name='SENHA'),
        ),
        migrations.AlterField(
            model_name='status',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa', verbose_name='PESSOA'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='idTipoTelefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.TipoTelefone', verbose_name='TIPO TELEFONE'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=11, verbose_name='NÚMERO'),
        ),
        migrations.AlterField(
            model_name='tipolotacao',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='TIPO LOTAÇÃO'),
        ),
        migrations.AlterField(
            model_name='tipotelefone',
            name='descricao',
            field=models.CharField(max_length=20, verbose_name='TIPO TELEFONE'),
        ),
    ]
