# Generated by Django 2.1.7 on 2019-04-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_auto_20190403_1915'),
        ('cadastros', '0006_auto_20190402_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='idEndereco',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='idEvento',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='idPessoa',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='idStatus',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='idOrgao',
        ),
        migrations.RemoveField(
            model_name='lotacao',
            name='idOrgao',
        ),
        migrations.RemoveField(
            model_name='lotacao',
            name='idPessoa',
        ),
        migrations.RemoveField(
            model_name='lotacao',
            name='idTipoLotacao',
        ),
        migrations.DeleteModel(
            name='Chamado',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Lotacao',
        ),
        migrations.DeleteModel(
            name='Orgao',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='TipoLotacao',
        ),
    ]
