# Generated by Django 2.1.7 on 2019-04-08 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='SERVIÇO')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=200, verbose_name='OBSERVAÇÃO')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotação',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='ÓRGÃO')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('descricao', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='TIPO LOTAÇÃO')),
            ],
            options={
                'verbose_name': 'Tipo Lotacao',
                'verbose_name_plural': 'Tipo Lotacao',
            },
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idOrgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao', verbose_name='ÓRGÃO'),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa', verbose_name='PESSOA'),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idTipoLotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.TipoLotacao', verbose_name='TIPO LOTAÇÃO'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='idOrgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao', verbose_name='ÓRGÃO'),
        ),
    ]
