# Generated by Django 2.2 on 2019-04-09 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='ÓRGÃO')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('descricao', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='TIPO LOTAÇÃO')),
            ],
            options={
                'verbose_name': 'Tipo Lotacao',
                'verbose_name_plural': 'Tipo Lotacao',
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=200, verbose_name='OBSERVAÇÃO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao', verbose_name='ÓRGÃO')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA')),
                ('idTipoLotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.TipoLotacao', verbose_name='TIPO LOTAÇÃO')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotação',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='SERVIÇO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao', verbose_name='ÓRGÃO')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
