# Generated by Django 2.1.7 on 2019-04-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20190403_1915'),
        ('orgao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lotacaos',
            new_name='Lotacao',
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='lotacao',
            options={'verbose_name': 'Lotação', 'verbose_name_plural': 'Lotação'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='tipolotacao',
            options={'verbose_name': 'TipoLotacao', 'verbose_name_plural': 'TipoLotacao'},
        ),
    ]
