# Generated by Django 2.2 on 2019-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0004_auto_20190406_1107'),
        ('orgao', '0002_auto_20190403_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
